export const adCategories = [
  { id: 'homeRentals', name: 'Home Rentals', emoji: '🏠', color: 'bg-blue-500' },
  { id: 'vehicles', name: 'Vehicles for Sale', emoji: '🚗', color: 'bg-green-500' },
  { id: 'vehicleLaunches', name: 'Vehicle Launches', emoji: '🏍️', color: 'bg-emerald-500' },
  { id: 'electronics', name: 'Electronics & Mobiles', emoji: '📱', color: 'bg-purple-500' },
  { id: 'mobileLaunches', name: 'Mobile Launches', emoji: '📲', color: 'bg-violet-500' },
  { id: 'furniture', name: 'Furniture', emoji: '🪑', color: 'bg-orange-500' },
  { id: 'jobs', name: 'Jobs & Requirements', emoji: '👔', color: 'bg-indigo-500' },
  { id: 'business', name: 'Showroom Offers', emoji: '🏢', color: 'bg-cyan-500' },
  { id: 'announcements', name: 'Local Announcements', emoji: '📢', color: 'bg-yellow-500' },
  { id: 'services', name: 'Services', emoji: '🧰', color: 'bg-teal-500' },
  { id: 'productSale', name: 'Product Sale', emoji: '🛒', color: 'bg-rose-500' },
];

export const adTypes = [
  { id: 'buy', label: 'For Sale' },
  { id: 'rent', label: 'For Rent' },
  { id: 'offer', label: 'Special Offer' },
  { id: 'announcement', label: 'Announcement' },
  { id: 'job', label: 'Job Posting' },
  { id: 'event', label: 'Event' },
  { id: 'launch', label: 'Product Launch' },
  { id: 'requirement', label: 'Requirement' },
];

// Dynamic form fields configuration for each category
export const categoryFormFields: Record<string, string[]> = {
  jobs: ['title', 'description', 'salary', 'jobType', 'experience', 'qualification', 'location', 'contact', 'validTill'],
  vehicleLaunches: ['title', 'description', 'launchDate', 'price', 'showroomName', 'features', 'images', 'location', 'contact'],
  mobileLaunches: ['title', 'description', 'launchDate', 'price', 'storeName', 'specifications', 'offers', 'images', 'location', 'contact'],
  business: ['title', 'description', 'offerDetails', 'validTill', 'termsConditions', 'images', 'location', 'contact'],
  homeRentals: ['title', 'description', 'price', 'propertyType', 'bhk', 'furnishing', 'deposit', 'images', 'location', 'contact'],
  vehicles: ['title', 'description', 'price', 'year', 'kmDriven', 'ownerType', 'fuelType', 'images', 'location', 'contact'],
  electronics: ['title', 'description', 'price', 'condition', 'warranty', 'brand', 'images', 'location', 'contact'],
  furniture: ['title', 'description', 'price', 'condition', 'material', 'images', 'location', 'contact'],
  productSale: ['title', 'description', 'price', 'category', 'condition', 'images', 'location', 'contact'],
  services: ['title', 'description', 'serviceType', 'pricing', 'availability', 'experience', 'location', 'contact'],
  announcements: ['title', 'description', 'eventDate', 'images', 'location', 'contact'],
};

// Mock advertisement data
export const mockAdvertisements = [
  {
    id: '1',
    title: 'New Royal Enfield Bullet 350 Launch',
    category: 'vehicleLaunches',
    type: 'launch',
    description: 'Grand launch of Royal Enfield Bullet 350 with special offers. Test rides available. First 10 bookings get free accessories worth ₹5,000.',
    price: '₹1,75,000 onwards',
    launchDate: '2025-10-20',
    showroomName: 'Royal Enfield Kumta Showroom',
    features: ['350cc Engine', 'Disc Brakes', 'LED Headlamp', 'Dual Channel ABS'],
    images: ['https://images.unsplash.com/photo-1558980663-3685c1d673c4?w=800'],
    location: 'Main Road, Kumta',
    postedBy: 'Royal Enfield Kumta',
    postedDate: '2025-10-14',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    email: 'info@rekumta.com',
    featured: true,
    sponsored: true,
    approved: true,
    tags: ['bike', 'launch', 'royalenfield', 'kumta'],
  },
  {
    id: '2',
    title: 'Sales Executive Required - Electronics Showroom',
    category: 'jobs',
    type: 'job',
    description: 'Urgent requirement for experienced Sales Executive for electronics showroom. Good communication skills required. Freshers can also apply.',
    salary: '₹15,000-₹20,000/month',
    jobType: 'Full-time',
    experience: '0-2 years',
    qualification: '12th Pass or Graduate',
    timing: '9 AM - 7 PM',
    validTill: '2025-10-30',
    images: [],
    location: 'Kumta Market Area',
    postedBy: 'Electronics Zone',
    postedDate: '2025-10-15',
    phone: '+91 98765 43211',
    whatsapp: '+91 98765 43211',
    featured: true,
    approved: true,
    tags: ['job', 'sales', 'kumta', 'urgent'],
  },
  {
    id: '3',
    title: '2BHK House for Rent - Family Preferred',
    category: 'homeRentals',
    type: 'rent',
    description: 'Spacious 2BHK house available for rent near Main Road. Semi-furnished with parking facility. Family preferred.',
    price: '₹8,000/month',
    propertyType: 'Independent House',
    bhk: '2 BHK',
    furnishing: 'Semi-Furnished',
    deposit: '₹16,000 (2 months)',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    location: 'Main Road, Kumta',
    postedBy: 'Ramesh Kumar',
    postedDate: '2025-10-13',
    phone: '+91 98765 43212',
    whatsapp: '+91 98765 43212',
    featured: false,
    approved: true,
    tags: ['house', 'rent', '2bhk', 'kumta'],
  },
  {
    id: '4',
    title: 'Samsung Galaxy S25 Launch - Special Offer',
    category: 'mobileLaunches',
    type: 'launch',
    description: 'Brand new Samsung Galaxy S25 now available! Limited time launch offer with exchange benefits and EMI facility. Get free Galaxy Buds worth ₹5,999 on purchase.',
    price: '₹79,999',
    launchDate: '2025-10-18',
    storeName: 'Mobile World Kumta',
    specifications: ['6.2" Display', '8GB RAM', '128GB Storage', '50MP Camera', '5000mAh Battery'],
    offers: 'Free Galaxy Buds + Exchange Bonus up to ₹10,000',
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800'],
    location: 'Mobile World, Kumta',
    postedBy: 'Mobile World',
    postedDate: '2025-10-15',
    phone: '+91 98765 43213',
    whatsapp: '+91 98765 43213',
    email: 'sales@mobileworld.com',
    featured: true,
    approved: true,
    tags: ['mobile', 'samsung', 'launch', 'kumta'],
  },
  {
    id: '5',
    title: 'Tata Punch 2025 - Grand Launch Event',
    category: 'vehicleLaunches',
    type: 'launch',
    description: 'New Tata Punch 2025 with advanced features and safety. Special launch offer with low down payment starting ₹25,000 and easy EMI options. Book now and get free accessories!',
    price: '₹6,49,000 onwards',
    launchDate: '2025-10-22',
    showroomName: 'Tata Motors Kumta',
    features: ['1.2L Turbo Engine', '5-Star Safety Rating', 'Sunroof', 'Digital Cluster', 'Connected Car Tech'],
    images: ['https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800'],
    location: 'Tata Motors Showroom, Kumta',
    postedBy: 'Tata Motors Kumta',
    postedDate: '2025-10-14',
    phone: '+91 98765 43214',
    whatsapp: '+91 98765 43214',
    email: 'sales@tatakumta.com',
    featured: true,
    approved: true,
    tags: ['car', 'tata', 'punch', 'launch'],
  },
  {
    id: '6',
    title: 'Kumta Cultural Festival - 20 Oct',
    category: 'announcements',
    type: 'announcement',
    description: 'Annual Kumta Cultural Festival featuring Yakshagana, folk dance, music programs, and food stalls. Entry free for all. Timing: 6 PM onwards.',
    eventDate: '2025-10-20',
    price: 'Free Entry',
    images: ['https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800'],
    location: 'Kumta Stadium Ground',
    postedBy: 'Kumta Cultural Association',
    postedDate: '2025-10-12',
    phone: '+91 98765 43215',
    whatsapp: '+91 98765 43215',
    featured: false,
    approved: true,
    tags: ['festival', 'cultural', 'yakshagana', 'kumta'],
  },
  {
    id: '7',
    title: 'Web Developer Required - IT Company',
    category: 'jobs',
    type: 'job',
    description: 'Looking for skilled Web Developer with React.js and Node.js experience. Work from home option available. Great learning opportunities.',
    salary: '₹25,000-₹40,000/month',
    jobType: 'Full-time / Part-time',
    experience: '1-3 years',
    qualification: 'BSc/BCA/BTech in Computer Science',
    validTill: '2025-11-15',
    images: [],
    location: 'Kumta / Remote',
    postedBy: 'TechSolutions Kumta',
    postedDate: '2025-10-16',
    phone: '+91 98765 43216',
    whatsapp: '+91 98765 43216',
    email: 'hr@techsolutions.com',
    featured: true,
    approved: true,
    tags: ['job', 'developer', 'remote', 'kumta'],
  },
  {
    id: '8',
    title: 'Big Diwali Sale - Electronics Showroom',
    category: 'business',
    type: 'offer',
    description: 'Mega Diwali sale on all electronics! Get up to 50% off on TVs, Refrigerators, Washing Machines, and more. EMI starting at ₹999/month.',
    offer: 'Flat 50% off + Exchange Bonus + No Cost EMI',
    offerValidTill: '11/4/2025',
    offerTerms: 'Terms and conditions apply. Offer valid on select models.',
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
    location: 'Electronics Mega Store, Kumta',
    postedBy: 'Electronics Mega Store',
    postedDate: '2025-10-15',
    phone: '+91 98765 43217',
    phone2: '+91 98765 43218',
    whatsapp: '+91 98765 43217',
    featured: true,
    approved: true,
    tags: ['sale', 'diwali', 'electronics', 'offer'],
  },
];
