export const categorySubcategories: Record<string, string[]> = {
  shops: [
    'Grocery Stores',
    'Medical Stores',
    'Furniture Shops',
    'Electronics',
    'Fashion & Clothing',
    'Hardware Stores',
    'Book Stores',
    'Gift Shops',
  ],
  temples: [
    'Hindu Temples',
    'Mosques',
    'Churches',
    'Other Religious Places',
  ],
  tourism: [
    'Beaches',
    'Historical Sites',
    'Parks & Gardens',
    'Waterfalls',
    'Viewpoints',
    'Adventure Activities',
  ],
  schoolsColleges: [
    'Primary Schools',
    'High Schools',
    'Pre-University Colleges',
    'Degree Colleges',
    'Professional Colleges',
    'Coaching Centers',
  ],
  services: [
    'Plumbing',
    'Electrical',
    'Carpentry',
    'Painting',
    'Cleaning Services',
    'Home Repairs',
    'Appliance Repair',
  ],
  associations: [
    'Community Associations',
    'Youth Clubs',
    'Women Groups',
    'Senior Citizen Groups',
    'Professional Associations',
  ],
  culturalPrograms: [
    'Yakshagana',
    'Classical Dance',
    'Music Programs',
    'Drama & Theater',
    'Festivals',
    'Cultural Events',
  ],
  departments: [
    'Government Offices',
    'Municipality',
    'Police Station',
    'Post Office',
    'Revenue Department',
    'Panchayat Office',
  ],
  doctors: [
    'General Physician',
    'Dentist',
    'Eye Specialist',
    'Orthopedic',
    'Pediatrician',
    'Dermatologist',
    'Gynecologist',
    'Cardiologist',
  ],
  emergencyServices: [
    'Ambulance Services',
    'Fire Station',
    'Police Station',
    'Hospital Emergency',
    '24/7 Medical Services',
  ],
  hotels: [
    'Budget Hotels',
    'Lodges',
    'Resorts',
    'Guest Houses',
    'Beach Resorts',
  ],
  rentVehicles: [
    'Car Rentals',
    'Bike Rentals',
    'Scooter Rentals',
    'Auto Rickshaw',
    'Bus Services',
  ],
  sportsEquipments: [
    'Cricket Equipment',
    'Football Equipment',
    'Badminton',
    'Swimming',
    'Gym Equipment',
    'Sports Wear',
  ],
};

export const subcategoryEmojis: Record<string, string> = {
  // Doctors
  'General Physician': '💊',
  'Dentist': '🦷',
  'Eye Specialist': '👁️',
  'Orthopedic': '🦴',
  'Pediatrician': '👶',
  'Dermatologist': '💆‍♀️',
  'Gynecologist': '👩‍⚕️',
  'Cardiologist': '❤️',
  
  // Tourism
  'Beaches': '🏖️',
  'Historical Sites': '🏛️',
  'Parks & Gardens': '🌳',
  'Waterfalls': '💧',
  'Viewpoints': '🌄',
  'Adventure Activities': '🧗',
  
  // Default emoji if not specified
  'default': '📍',
};
